apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-juice-shop
  labels:
    app: snyk-juice-shop
spec:
  selector:
    matchLabels:
      app: snyk-juice-shop
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: snyk-juice-shop
    spec:
      containers:
      - name: juice-shop
        image: troysnyk/snyk-juice-shop:linux
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
